var questions = [
  // sebagai array yang menyimpan kumpulan data pertnyaan
  [
    "Apa kepanjangan dari HTML??",
    "Hyper Text Markup Language",
    "Home Tool Markup Language",
    "Hyperlinks and Text Markup Language",
    "Hyperlinking Text Marking Languagene",
    "1",
  ],
  [
    "Apa itu HTML?",
    "Bahasa pemrograman",
    "Bahasa markup",
    "Bahasa query",
    "Bahasa script",
    "2",
  ],
  [
    "Manakah dari berikut ini yang merupakan sistem operasi open-source?",
    "Windows",
    "macOS",
    "Linux",
    "iOS",
    "3",
  ],
  [
    "Apa kepanjangan dari CPU?",
    "Central Processing Unit",
    "Central Program Unit",
    "Control Processing Unit",
    "Computer Processing Unit",
    "1",
  ],
  [
    "Apa fungsi utama dari RAM dalam komputer?",
    "Penyimpanan permanen data",
    "Memproses instruksi",
    "Penyimpanan sementara data",
    "Mengelola perangkat lunak",
    "3",
  ],
  [
    "Manakah dari berikut ini yang bukan merupakan bahasa pemrograman?",
    "Python",
    "Java",
    "SQL",
    "HTML",
    "4",
  ],
  [
    "Manakah dari berikut ini yang merupakan protokol untuk transfer file di internet?",
    "HTTP",
    "FTP",
    "SMTP",
    "DNS",
    "2",
  ],
  [
    "Manakah dari berikut ini yang merupakan aplikasi pengolah kata?",
    "Adobe Photoshop",
    "Microsoft Excel",
    "Microsoft Word",
    "VLC Media Player",
    "3",
  ],
  [
    "Apa itu cloud computing?",
    "Penyimpanan data di perangkat lokal",
    "Komputasi yang menggunakan sumber daya lokal",
    "Penyimpanan dan pengelolaan data melalui internet",
    "Menggunakan komputer dengan performa tinggi",
    "3",
  ],
  [
    "Apa kepanjangan dari URL?",
    "Uniform Resource Locator",
    "Uniform Resource Link",
    "Universal Resource Locator",
    "Universal Resource Link",
    "1",
  ],
  [
    "Manakah dari berikut ini yang merupakan contoh perangkat lunak sumber terbuka (open-source)?",
    "Microsoft Office",
    "Adobe Photoshop",
    "Mozilla Firefox",
    "AutoCAD",
    "3",
  ],
  [
    "Apa fungsi dari perangkat lunak antivirus?",
    "Meningkatkan kecepatan komputer",
    "Melindungi komputer dari malware",
    "Mengedit video",
    "Mengelola database",
    "2",
  ],
];
